@base_url=http://localhost:4500
GET http://localhost:4500/users


GET @base_url/

###

POST http://localhost:4500/v1/auth/register HTTP/1.1 
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Wick",
    "email": "john.wick_07@example.com",
    "password": "password123"
}